// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConversationMessage is a normalized transcript entry for one session.
 */
export interface ConversationMessage {
    "id": string;

    /**
     * user, assistant, system, synthetic, shell, skill
     */
    "role": string;
    "agent"?: string;
    "model"?: string;
    "text"?: string;
    "reasoning"?: string;
    "tools"?: ToolCall[] | null;
    "createdAt": number;
    "completedAt"?: number;
}

/**
 * ConversationPage is one page of a session transcript, ordered oldest-first.
 * NextCursor points at the next page of older messages when HasMore is true.
 */
export interface ConversationPage {
    "messages": ConversationMessage[] | null;
    "nextCursor"?: string;
    "hasMore": boolean;
}

/**
 * HarnessInfo describes one selectable harness or device.
 */
export interface HarnessInfo {
    "id": string;
    "name": string;
    "description"?: string;
    "local": boolean;
    "online": boolean;
}

/**
 * McpInfo describes one configured MCP server.
 */
export interface McpInfo {
    "name": string;
    "status": string;
    "active": boolean;
}

/**
 * OpenCodeStatus describes the state of the OpenCode2 service.
 */
export interface OpenCodeStatus {
    "ready": boolean;
    "url": string;
    "error": string;
}

/**
 * PluginInfo describes one plugin and whether it is currently enabled.
 */
export interface PluginInfo {
    "id": string;
    "active": boolean;
}

/**
 * ProjectInfo is a frontend-friendly projection of an OpenCode2 project.
 */
export interface ProjectInfo {
    "id": string;
    "canonical": string;
    "name"?: string;
    "vcs"?: string;
    "updatedAt": number;
}

/**
 * SessionInfo is a frontend-friendly projection of an OpenCode2 session.
 */
export interface SessionInfo {
    "id": string;
    "parentId"?: string;
    "projectId": string;
    "agent"?: string;
    "title": string;
    "directory"?: string;
    "subpath"?: string;
    "createdAt": number;
    "updatedAt": number;
    "active": boolean;
}

/**
 * SkillInfo describes one loaded skill.
 */
export interface SkillInfo {
    "id": string;
    "name": string;
    "description"?: string;
    "location"?: string;
    "active": boolean;
}

/**
 * SubagentInfo is a child session that was spawned by a parent session.
 */
export interface SubagentInfo {
    "id": string;
    "parentId": string;
    "agent"?: string;
    "title": string;
    "status": string;
    "messages": ConversationMessage[] | null;
}

/**
 * ToolCall is a single tool invocation embedded in an assistant message.
 */
export interface ToolCall {
    "id": string;
    "name": string;
    "status": string;
    "input"?: string;
    "output"?: string;
    "diff"?: string;
    "createdAt"?: number;
    "completedAt"?: number;
}
