// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OpenCodeStatus describes the state of the OpenCode2 service.
 */
export interface OpenCodeStatus {
    "ready": boolean;
    "url": string;
    "error": string;
}
