// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OpenCodeService expune către frontend verificarea statusului
 * și setup-ul serviciului OpenCode2.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * IsReady verifică dacă serviciul OpenCode2 rulează.
 */
export function IsReady(): $CancellablePromise<$models.OpenCodeStatus> {
    return $Call.ByID(1524974339);
}

/**
 * Setup instalează CLI-ul OpenCode2 dacă lipsește și pornește serviciul.
 */
export function Setup(): $CancellablePromise<$models.OpenCodeStatus> {
    return $Call.ByID(3837683321);
}
