// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OpenCodeService exposes status checking and OpenCode2 service setup to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * IsReady checks whether the OpenCode2 service is running.
 */
export function IsReady(): $CancellablePromise<$models.OpenCodeStatus> {
    return $Call.ByID(1524974339);
}

/**
 * Setup installs the OpenCode2 CLI if missing and starts the service.
 */
export function Setup(): $CancellablePromise<$models.OpenCodeStatus> {
    return $Call.ByID(3837683321);
}
